version: '2.1'
services:
  # https://github.com/balena-io-projects/balena-wpe
  Browser:
    restart: always
    build: ./balena-wpe
    privileged: true
    network_mode: host
    environment:
      INITSYSTE: on
      WPE_URL: http://localhost:90
    depends_on:
      - mm
    command: >
      /bin/bash -c "
        while ! wget -O /dev/null $WPE_URL > /dev/null;
        do
          echo 'Waiting for MagicMirror to be ready...';
          sleep 10;
          exit 1;
        done;
        echo 'MagicMirror up, starting the Browser now!';
        /wpe-init
      "
  mm:
    restart: always
    build: ./MagicMirror
    privileged: true
    network_mode: host